name: Test Retroblog

on:
  - push
  - schedule:
    - cron: '0 4 * * *'

jobs:
  Lint-and-Test:
    name: Lint-and-Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        mkdir bin
        cd bin
        sudo apt install -y curl unzip build-essential python3
        curl --output chromedriver.zip https://chromedriver.storage.googleapis.com/98.0.4758.102/chromedriver_linux64.zip
        unzip chromedriver.zip
        rm chromedriver.zip
    - name: Pylint
      run: | 
        pip install -r requirements.txt
        pylint --extension-pkg-whitelist='pydantic' --fail-under=4 ./tests/
    - name: PyTest
      run: | 
        pip install -r requirements.txt
        python -m pytest ./tests/*.py
