name: Test Retroblog

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  Lint-and-Test:
    name: Lint-and-Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          mkdir bin
          cd bin
          sudo apt install -y curl unzip build-essential python3
          curl --output chromedriver.zip https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
          unzip chromedriver.zip
          rm chromedriver.zip
      - name: Pylint
        run: |
          pip install -r requirements.txt
          pylint --extension-pkg-whitelist='pydantic' --fail-under=4 ./tests/
      - name: PyTest
        run: |
          pip install -r requirements.txt
          python -m pytest ./tests/*.py
